Thieverypack(Thief, the Deceiver) Rework
erasels/PackmasterCharacter pull request #215
Opened 2023-01-17 19:31 UTC by Celicath

I did a few runs with my pack. My thoughts:
- Strength stealing feels great. There are many enemies that gain Strength themselves, and it really feels like you are stealing their powers.
- Magnet and Null Hammer feels really bad because they miss a lot.
- Cunning power is OP
- Other cards are just ok, but they could benefit from small number buffs.

With this in mind, I made these changes:
| Old | New | Notes |
|-------|-------|------|
| ![image](https://user-images.githubusercontent.com/1008668/212989855-5ce76c68-16fd-4fb1-92e8-14a541d6d47e.png) | ![image](https://user-images.githubusercontent.com/1008668/212990074-d8bd1daf-e7ce-4d89-9738-aec915bcd47a.png) | Cunning Poison is a completely different, gold-stealing card. Now the thief can steal money. |
| ![image](https://user-images.githubusercontent.com/1008668/212991413-530cd000-1011-436b-bf0d-6392b908a04e.png) | ![image](https://user-images.githubusercontent.com/1008668/212991442-e62db542-a361-4471-abd4-14f36f7740bb.png) | Magnet felt good when it actually stole Artifact, but there are only a few enemies that have them. Now magnet can steal all metal-ish powers, hopefully giving it more chances. Magnet upgrades to ALL enemies. |
| ![image](https://user-images.githubusercontent.com/1008668/212992170-a8690044-34f6-49c8-b436-86b460c2d19b.png) | ![image](https://user-images.githubusercontent.com/1008668/212992074-0742d1d3-2523-45e7-9767-a139cb035cc1.png) | This was almost a pure damage card, now it's more spicy. |
| ![image](https://user-images.githubusercontent.com/1008668/212992359-d87072f3-1fa1-463a-aa9c-9ca52cdff275.png) ![image](https://user-images.githubusercontent.com/1008668/212992397-df297dc0-6a43-458a-822e-5140d70f2605.png) | ![image](https://user-images.githubusercontent.com/1008668/212992534-d9bba60c-389c-49e0-bc9f-f51155089e62.png) ![image](https://user-images.githubusercontent.com/1008668/212992551-068ca1de-716f-4e7c-aa08-efcfcfeb29c0.png) | They needed this buff. |
| ![image](https://user-images.githubusercontent.com/1008668/212992687-09e81078-3c2c-469c-8a81-573269e062ec.png) | ![image](https://user-images.githubusercontent.com/1008668/212992731-989a17d1-118f-4455-9053-19467eb439cb.png) | Thievery Mastery no longer stacks. Boo! But this allowed me to create gold-stealing card, because it's much harder to copy Skills than Powers. You can still get infinite gold by copying Cunning Poison over and over, it's unfortunate but I didn't want to make the card super complex to prevent this. |

Cardbacks are slightly adjusted, a few bugs were fixed.

2023-01-17 19:59 UTC, erasels commented
Magnet -> from enemy = from the enemy
Cunning poison -> highest HP
Thanks for the great explanation, I appreciate the effort you put into this.

2023-01-17 20:04 UTC, erasels requested changes

2023-01-17 20:04 UTC, erasels commented on src/main/java/thePackmaster/actions/thieverypack/StealPowerAction.java
> +							if (AbstractDungeon.player.hand.size() != 10) {
```suggestion
							if (AbstractDungeon.player.hand.size() != BaseMod.MAX_HAND_SIZE) {
```
requires import

2023-01-18 00:14 UTC, Celicath commented
Thanks for the suggestions, I changed them.

2023-01-18 07:35 UTC, erasels commented on src/main/java/thePackmaster/actions/thieverypack/StealPowerAction.java
> +							if (AbstractDungeon.player.hand.size() != BaseMod.MAX_HAND_SIZE) {
```suggestion
							if (AbstractDungeon.player.hand.size() < BaseMod.MAX_HAND_SIZE) {
```

2023-01-18 07:36 UTC, erasels approved these changes

2023-01-18 07:36 UTC, merged