- added quantapack and started metapack
erasels/PackmasterCharacter pull request #32
Opened 2023-01-04 00:52 UTC by AlexMdle

2023-01-04 08:49 UTC, erasels commented
Generally, I'd like packs to have completed art when PRed, and one pack per PR is also preferred.
I'll wait with merging until you've added the art unless it contains mechanics important for other packs.

2023-01-04 21:44 UTC, AlexMdle commented
Added missing art.

2023-01-04 23:16 UTC, erasels requested changes

2023-01-04 23:16 UTC, erasels commented on src/main/java/thePackmaster/cards/quantapack/MagicDart.java
> +        if (!upgraded) {
Will never happen because upgradeName is called before upp which sets upgraded to true

2023-01-04 23:16 UTC, erasels commented on src/main/java/thePackmaster/cards/quantapack/MagicDart.java
> +        this.calculateCardDamage(m);
What is happening here? baseDamage should be modified in applyPowers and calculateCardDamage methods, not what you're doing here.

Also, once you've fixed the upp method issue, you don't need to do this getMyName() stuff anymore.

2023-01-04 23:16 UTC, erasels commented on src/main/java/thePackmaster/cards/quantapack/Manaburst.java
> +        this.addToBot(new ManaburstAction(this.magicNumber, CardType.ATTACK));
You need to replace this action with what's described on the action itself.

2023-01-04 23:16 UTC, erasels commented on src/main/java/thePackmaster/powers/quantapack/IchorGobletPower.java
> +        this.addToBot(new ReducePowerAction(this.owner, AbstractDungeon.player, this, 1));
```suggestion
        this.addToBot(new ReducePowerAction(this.owner, this.owner, this, 1));
```

2023-01-04 23:16 UTC, erasels commented on src/main/resources/anniv5Resources/localization/eng/quantapack/Cardstrings.json
> +    "DESCRIPTION": "Deal !D! damage, then deal !M! damage to ALL enemies."
```suggestion
    "DESCRIPTION": "Deal !D! damage. NL Deal !M! damage to ALL enemies."
```

2023-01-04 23:16 UTC, erasels commented on src/main/resources/anniv5Resources/localization/eng/quantapack/Cardstrings.json
> +    "UPGRADE_DESCRIPTION": "Apply !M! ${ModID}:Stun to ALL enemies. NL Exhaust."
Generally it's worded as `Stun the enemy.` maybe add a for X turns if it's more than 1.

2023-01-04 23:33 UTC, erasels commented on src/main/java/thePackmaster/actions/quantapack/ManaburstAction.java
> +                    if (this.p.hand.size() == 10) {
Hardcoded max hand size check. BaseMod.MAX_HAND_SIZE must be used

2023-01-05 20:56 UTC, AlexMdle commented
All changes up.

2023-01-05 21:01 UTC, erasels approved these changes

2023-01-05 21:01 UTC, merged