Enchanter pack
erasels/PackmasterCharacter pull request #560
Opened 2023-04-02 20:07 UTC by Pandemonium14

Full transparency about the hand ordering, because we had a discussion about it :
While a hand select screen is up, the hand order does not change. Cards added to the hand as a result of the action with a AddTempCardInHand action are put to the right.
The one wrinkle it has is with actions that open a hand select screen and say, add a modifier to the selected card, because then, after clicking Done, the card is put to the right of the hand, not in its original place. This is consistent still, so I'm personally okay with it, but maybe you're not?
I don't immediately see how to change that behavior, but if it bothers you, just say so and I'll try to fix the issue.

2023-04-03 18:08 UTC, erasels requested changes

2023-04-03 18:08 UTC, erasels commented on src/main/resources/anniv5Resources/localization/eng/artificerpack/Cardstrings.json
> +    "DESCRIPTION": "Unplayable. NL When you play an adjacent card, a random enemy takes !M! damage."
Hmm, wouldn't it be Whenever here?

2023-04-03 19:57 UTC, Pandemonium14 commented
Should be done? I'm not sure what else to do about Boost's wording tbh

2023-04-03 21:49 UTC, erasels requested changes

2023-04-03 21:49 UTC, erasels commented on src/main/java/thePackmaster/cardmodifiers/artificerpack/BlockEnchantModifier.java
> +            CardModifierManager.removeSpecificModifier(card, this, true);
Might want to make this an anonymous action. This could lead to a conc mod exception

2023-04-04 16:09 UTC, Pandemonium14 commented
Done!

2023-04-04 19:41 UTC, merged